dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/

ignore:
  - src/frontend/

cache:
  directories:
    - ./node_modules

install:
  - pushd $TRAVIS_BUILD_DIR
  - npm install

script:
  - npm run build:travis

notifications:
  email:
    recipients:
      - waltervfaustine@gmail.com

    on_failure: always
    on_success: always
  
  slack: hisptz:2UQgrRwNrI14ohefnnPyzms7

