dist: bionic

language: node_js
node_js:
  - 12
cache: npm
jobs:
  include:
    - stage: test
      script:
        - echo 'Installing Dependencies'
        - npm
        - echo 'Running integration tests!'
        - npx jest test

script:
  - npm run build

notifications:
  slack: hisptz:2UQgrRwNrI14ohefnnPyzms7